### ISSUE TITLE
Registrations Controller

### ISSUE THREAD

**Issue by dsiver** [dsiver/SnapTrivia#71]
While working on adding trophies with Merit, I wondered how it was working because I did not find overrides of the Devise Registration controller's 'update' and 'create' methods in the class I wrote.

After digging further, I discovered another controller had been created when Merit was installed on April 2 (commit: https://github.com/dsiver/SnapTrivia/commit/f224d91c518a9a5337f7fed570432e241b3a1ee6 controller: https://github.com/dsiver/SnapTrivia/commit/9ddf29e76f1b9676c41eab2cca27ad0fbd66b3b5#diff-107c009feef83ea12f774836bb3e6a4b).

Also, modifications were made to 'config/routes.rb' (https://github.com/dsiver/SnapTrivia/commit/9ddf29e76f1b9676c41eab2cca27ad0fbd66b3b5#diff-21497849d8f00507c9c8dcaf6288b136) at this time, changing the 'devise_for registrations:' from 'registrations' to 'users/registrations'. If this was not caught, the existing overrides in the original registrations controller would no longer work, breaking functionality.

I looked at the tutorial for Merit. It said to do this. However, 'routes.rb' already contained a registrations setting.

I fixed it and my next push will reflect those changes.

**Comment by kchasta2** [comment]
This was something I was going to ask you about.  After I added the New User badge, I noticed it wasn't working for Facebook and Google+.  I figured it had something to do with the new controller and change to the routes.rb because I didn't know where the "action" was happening for those two types of registrations.  My plan was to take that out until I could talk to you about it, then I forgot as we started focusing on other issues.

Thanks for fixing it.
